import type { Asset } from "../types/types";

export const MOCK_ASSETS: Asset[] = [
  // Equities - ETF
  {
    id: "1",
    ticker: "VOO",
    name: "Vanguard S&P 500 ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+28.5%", "3Y": "+12.3%", "5Y": "+15.8%" },
    exchange: "NYSE",
  },
  {
    id: "2",
    ticker: "VTI",
    name: "Vanguard Total Stock Market ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+26.8%", "3Y": "+11.9%", "5Y": "+14.2%" },
    exchange: "NYSE",
  },
  {
    id: "3",
    ticker: "QQQ",
    name: "Invesco QQQ Trust",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+32.1%", "3Y": "+15.7%", "5Y": "+18.9%" },
    exchange: "NASDAQ",
  },
  {
    id: "4",
    ticker: "VEA",
    name: "Vanguard FTSE Developed Markets ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+18.2%", "3Y": "+8.4%", "5Y": "+9.1%" },
    exchange: "NYSE",
  },
  {
    id: "5",
    ticker: "VWO",
    name: "Vanguard FTSE Emerging Markets ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+12.5%", "3Y": "+3.2%", "5Y": "+5.8%" },
    exchange: "NYSE",
  },
  {
    id: "6",
    ticker: "IWM",
    name: "iShares Russell 2000 ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+22.3%", "3Y": "+9.1%", "5Y": "+11.4%" },
    exchange: "NYSE",
  },
  {
    id: "7",
    ticker: "VGT",
    name: "Vanguard Information Technology ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+35.2%", "3Y": "+18.5%", "5Y": "+22.1%" },
    exchange: "NYSE",
  },
  {
    id: "8",
    ticker: "VYM",
    name: "Vanguard High Dividend Yield ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+14.8%", "3Y": "+9.2%", "5Y": "+10.5%" },
    exchange: "NYSE",
  },

  // Equities - Direct Stock
  {
    id: "9",
    ticker: "AAPL",
    name: "Apple Inc",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+48.2%", "3Y": "+22.5%", "5Y": "+25.3%" },
    exchange: "NASDAQ",
  },
  {
    id: "10",
    ticker: "MSFT",
    name: "Microsoft Corporation",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+38.5%", "3Y": "+19.8%", "5Y": "+23.7%" },
    exchange: "NASDAQ",
  },
  {
    id: "11",
    ticker: "GOOGL",
    name: "Alphabet Inc Class A",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+42.1%", "3Y": "+17.2%", "5Y": "+20.4%" },
    exchange: "NASDAQ",
  },
  {
    id: "12",
    ticker: "AMZN",
    name: "Amazon.com Inc",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+52.3%", "3Y": "+18.9%", "5Y": "+19.8%" },
    exchange: "NASDAQ",
  },
  {
    id: "13",
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+239.1%", "3Y": "+112.5%", "5Y": "+98.3%" },
    exchange: "NASDAQ",
  },
  {
    id: "14",
    ticker: "TSLA",
    name: "Tesla Inc",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "-24.2%", "3Y": "+31.5%", "5Y": "+45.2%" },
    exchange: "NASDAQ",
  },
  {
    id: "15",
    ticker: "META",
    name: "Meta Platforms Inc",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+194.2%", "3Y": "+45.8%", "5Y": "+28.3%" },
    exchange: "NASDAQ",
  },
  {
    id: "16",
    ticker: "BRK.B",
    name: "Berkshire Hathaway Inc Class B",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+18.5%", "3Y": "+12.1%", "5Y": "+14.8%" },
    exchange: "NYSE",
  },
  {
    id: "17",
    ticker: "JPM",
    name: "JPMorgan Chase & Co",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+38.2%", "3Y": "+15.3%", "5Y": "+13.7%" },
    exchange: "NYSE",
  },
  {
    id: "18",
    ticker: "V",
    name: "Visa Inc Class A",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+22.5%", "3Y": "+14.8%", "5Y": "+16.2%" },
    exchange: "NYSE",
  },

  // Equities - Mutual Fund
  {
    id: "19",
    ticker: "VFIAX",
    name: "Vanguard 500 Index Fund Admiral",
    category: "Equities",
    instrument: "Mutual Fund",
    returns: { "1Y": "+28.3%", "3Y": "+12.2%", "5Y": "+15.7%" },
    exchange: "NASDAQ",
  },
  {
    id: "20",
    ticker: "FXAIX",
    name: "Fidelity 500 Index Fund",
    category: "Equities",
    instrument: "Mutual Fund",
    returns: { "1Y": "+28.2%", "3Y": "+12.1%", "5Y": "+15.6%" },
    exchange: "NASDAQ",
  },
  {
    id: "21",
    ticker: "VTSAX",
    name: "Vanguard Total Stock Market Index Admiral",
    category: "Equities",
    instrument: "Mutual Fund",
    returns: { "1Y": "+26.7%", "3Y": "+11.8%", "5Y": "+14.1%" },
    exchange: "NASDAQ",
  },
  {
    id: "22",
    ticker: "VTSMX",
    name: "Vanguard Total Stock Market Index Investor",
    category: "Equities",
    instrument: "Mutual Fund",
    returns: { "1Y": "+26.5%", "3Y": "+11.7%", "5Y": "+14.0%" },
    exchange: "NASDAQ",
  },
  {
    id: "23",
    ticker: "VGTSX",
    name: "Vanguard Total International Stock Index",
    category: "Equities",
    instrument: "Mutual Fund",
    returns: { "1Y": "+16.2%", "3Y": "+7.1%", "5Y": "+8.5%" },
    exchange: "NASDAQ",
  },
  {
    id: "24",
    ticker: "VIGAX",
    name: "Vanguard Growth Index Admiral",
    category: "Equities",
    instrument: "Mutual Fund",
    returns: { "1Y": "+35.8%", "3Y": "+15.2%", "5Y": "+18.3%" },
    exchange: "NASDAQ",
  },
  {
    id: "25",
    ticker: "VVIAX",
    name: "Vanguard Value Index Admiral",
    category: "Equities",
    instrument: "Mutual Fund",
    returns: { "1Y": "+20.5%", "3Y": "+9.5%", "5Y": "+12.8%" },
    exchange: "NASDAQ",
  },

  // Bonds - ETF
  {
    id: "26",
    ticker: "BND",
    name: "Vanguard Total Bond Market ETF",
    category: "Bonds",
    instrument: "ETF",
    returns: { "1Y": "+5.2%", "3Y": "-2.1%", "5Y": "+0.8%" },
    exchange: "NASDAQ",
  },
  {
    id: "27",
    ticker: "AGG",
    name: "iShares Core U.S. Aggregate Bond ETF",
    category: "Bonds",
    instrument: "ETF",
    returns: { "1Y": "+5.1%", "3Y": "-2.2%", "5Y": "+0.7%" },
    exchange: "NYSE",
  },
  {
    id: "28",
    ticker: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    category: "Bonds",
    instrument: "ETF",
    returns: { "1Y": "+3.8%", "3Y": "-8.5%", "5Y": "-2.3%" },
    exchange: "NASDAQ",
  },
  {
    id: "29",
    ticker: "LQD",
    name: "iShares iBoxx Investment Grade Corporate Bond ETF",
    category: "Bonds",
    instrument: "ETF",
    returns: { "1Y": "+7.2%", "3Y": "-1.5%", "5Y": "+1.8%" },
    exchange: "NYSE",
  },
  {
    id: "30",
    ticker: "HYG",
    name: "iShares iBoxx High Yield Corporate Bond ETF",
    category: "Bonds",
    instrument: "ETF",
    returns: { "1Y": "+10.8%", "3Y": "+2.5%", "5Y": "+4.2%" },
    exchange: "NYSE",
  },
  {
    id: "31",
    ticker: "MUB",
    name: "iShares National Muni Bond ETF",
    category: "Bonds",
    instrument: "ETF",
    returns: { "1Y": "+4.5%", "3Y": "-1.8%", "5Y": "+1.2%" },
    exchange: "NYSE",
  },
  {
    id: "32",
    ticker: "VCIT",
    name: "Vanguard Intermediate-Term Corporate Bond ETF",
    category: "Bonds",
    instrument: "ETF",
    returns: { "1Y": "+6.8%", "3Y": "-1.2%", "5Y": "+1.5%" },
    exchange: "NASDAQ",
  },
  {
    id: "33",
    ticker: "BNDX",
    name: "Vanguard Total International Bond ETF",
    category: "Bonds",
    instrument: "ETF",
    returns: { "1Y": "+3.2%", "3Y": "-3.5%", "5Y": "-0.8%" },
    exchange: "NASDAQ",
  },

  // Bonds - Mutual Fund
  {
    id: "34",
    ticker: "VBTLX",
    name: "Vanguard Total Bond Market Index Admiral",
    category: "Bonds",
    instrument: "Mutual Fund",
    returns: { "1Y": "+5.1%", "3Y": "-2.2%", "5Y": "+0.7%" },
    exchange: "NASDAQ",
  },
  {
    id: "35",
    ticker: "VBMFX",
    name: "Vanguard Total Bond Market Index Investor",
    category: "Bonds",
    instrument: "Mutual Fund",
    returns: { "1Y": "+5.0%", "3Y": "-2.3%", "5Y": "+0.6%" },
    exchange: "NASDAQ",
  },
  {
    id: "36",
    ticker: "FXNAX",
    name: "Fidelity U.S. Bond Index Fund",
    category: "Bonds",
    instrument: "Mutual Fund",
    returns: { "1Y": "+5.1%", "3Y": "-2.1%", "5Y": "+0.8%" },
    exchange: "NASDAQ",
  },
  {
    id: "37",
    ticker: "VWITX",
    name: "Vanguard Intermediate-Term Tax-Exempt",
    category: "Bonds",
    instrument: "Mutual Fund",
    returns: { "1Y": "+4.2%", "3Y": "-1.5%", "5Y": "+1.0%" },
    exchange: "NASDAQ",
  },
  {
    id: "38",
    ticker: "VWEHX",
    name: "Vanguard High-Yield Corporate",
    category: "Bonds",
    instrument: "Mutual Fund",
    returns: { "1Y": "+10.5%", "3Y": "+2.3%", "5Y": "+4.0%" },
    exchange: "NASDAQ",
  },
  {
    id: "39",
    ticker: "PIMIX",
    name: "PIMCO Income Fund Institutional",
    category: "Bonds",
    instrument: "Mutual Fund",
    returns: { "1Y": "+8.2%", "3Y": "+1.5%", "5Y": "+2.8%" },
    exchange: "NASDAQ",
  },
  {
    id: "40",
    ticker: "DODIX",
    name: "Dodge & Cox Income Fund",
    category: "Bonds",
    instrument: "Mutual Fund",
    returns: { "1Y": "+6.5%", "3Y": "-0.8%", "5Y": "+1.5%" },
    exchange: "NASDAQ",
  },

  // Additional Equities - ETF
  {
    id: "41",
    ticker: "VUG",
    name: "Vanguard Growth ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+35.5%", "3Y": "+15.1%", "5Y": "+18.2%" },
    exchange: "NYSE",
  },
  {
    id: "42",
    ticker: "VTV",
    name: "Vanguard Value ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+20.8%", "3Y": "+9.7%", "5Y": "+13.1%" },
    exchange: "NYSE",
  },
  {
    id: "43",
    ticker: "VNQ",
    name: "Vanguard Real Estate ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+8.5%", "3Y": "+2.1%", "5Y": "+5.8%" },
    exchange: "NYSE",
  },
  {
    id: "44",
    ticker: "VDE",
    name: "Vanguard Energy ETF",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+12.3%", "3Y": "+18.5%", "5Y": "+12.8%" },
    exchange: "NYSE",
  },
  {
    id: "45",
    ticker: "XLK",
    name: "Technology Select Sector SPDR Fund",
    category: "Equities",
    instrument: "ETF",
    returns: { "1Y": "+34.8%", "3Y": "+18.2%", "5Y": "+21.5%" },
    exchange: "NYSE",
  },

  // Additional Direct Stocks
  {
    id: "46",
    ticker: "JNJ",
    name: "Johnson & Johnson",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+8.2%", "3Y": "+5.1%", "5Y": "+7.3%" },
    exchange: "NYSE",
  },
  {
    id: "47",
    ticker: "PG",
    name: "Procter & Gamble Co",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+12.5%", "3Y": "+8.9%", "5Y": "+10.2%" },
    exchange: "NYSE",
  },
  {
    id: "48",
    ticker: "UNH",
    name: "UnitedHealth Group Inc",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+22.8%", "3Y": "+16.5%", "5Y": "+18.9%" },
    exchange: "NYSE",
  },
  {
    id: "49",
    ticker: "HD",
    name: "Home Depot Inc",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+15.2%", "3Y": "+8.5%", "5Y": "+12.3%" },
    exchange: "NYSE",
  },
  {
    id: "50",
    ticker: "DIS",
    name: "Walt Disney Co",
    category: "Equities",
    instrument: "Direct stock",
    returns: { "1Y": "+5.8%", "3Y": "-2.1%", "5Y": "+3.5%" },
    exchange: "NYSE",
  },
];
